// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3zC4fkbXrqgM7fa4uUQ6gc
// Component: b5vzjRTME0bP
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_abc.module.css"; // plasmic-import: 3zC4fkbXrqgM7fa4uUQ6gc/projectcss
import sty from "./PlasmicCompletedTweet.module.css"; // plasmic-import: b5vzjRTME0bP/css
import CommentIcon from "./icons/PlasmicIcon__Comment"; // plasmic-import: x_fBhSe4r8eDP/icon
import RefreshIcon from "./icons/PlasmicIcon__Refresh"; // plasmic-import: 5Inzcklc5x3s_/icon
import HeartIcon from "./icons/PlasmicIcon__Heart"; // plasmic-import: 5VnbFq94xyRIw/icon
import UploadIcon from "./icons/PlasmicIcon__Upload"; // plasmic-import: pRzhvAlYP-XWZ/icon

export const PlasmicCompletedTweet__VariantProps = new Array();

export const PlasmicCompletedTweet__ArgProps = new Array();

function PlasmicCompletedTweet__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"64px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"none"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"64px"}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__iCh2Y)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__hDeYt
          )}
        >
          {"Mark Dalgleish"}
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__lWuyM
          )}
        >
          {
            "Other industries figured out a long time ago that you can't go straight from concept design to construction. If we want to do design systems right, we're missing a step."
          }
        </div>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__eyBiQ)}
        >
          <CommentIcon
            className={classNames(projectcss.all, sty.svg__rTxfu)}
            role={"img"}
          />

          <RefreshIcon
            className={classNames(projectcss.all, sty.svg__oToTy)}
            role={"img"}
          />

          <HeartIcon
            className={classNames(projectcss.all, sty.svg__fNCpT)}
            role={"img"}
          />

          <UploadIcon
            className={classNames(projectcss.all, sty.svg__bqTg)}
            role={"img"}
          />
        </p.Stack>
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCompletedTweet__ArgProps,
          internalVariantPropNames: PlasmicCompletedTweet__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCompletedTweet__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedTweet";
  } else {
    func.displayName = `PlasmicCompletedTweet.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedTweet = Object.assign(
  // Top-level PlasmicCompletedTweet renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicCompletedTweet
    internalVariantProps: PlasmicCompletedTweet__VariantProps,
    internalArgProps: PlasmicCompletedTweet__ArgProps
  }
);

export default PlasmicCompletedTweet;
/* prettier-ignore-end */
