// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3zC4fkbXrqgM7fa4uUQ6gc
// Component: Ibk58H-q1HvXP
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_abc.module.css"; // plasmic-import: 3zC4fkbXrqgM7fa4uUQ6gc/projectcss
import sty from "./PlasmicLandmarks.module.css"; // plasmic-import: Ibk58H-q1HvXP/css
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: qyDbFYfpaFHMy/icon

export const PlasmicLandmarks__VariantProps = new Array("variants");

export const PlasmicLandmarks__ArgProps = new Array();

function PlasmicLandmarks__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variants",
        type: "private",
        initFunc: ($props, $state, $ctx) => $props.variants
      }
    ],

    [$props, $ctx]
  );

  const $state = p.useDollarState(stateSpecs, $props, $ctx);
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        { [sty.rootvariants_wide]: hasVariant($state, "variants", "wide") }
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__wJv24,
          {
            [sty.textvariants_wide__wJv24H3VVh]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          }
        )}
      >
        {"Landmarks"}
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__qjr30, {
          [sty.freeBoxvariants_wide__qjr30H3VVh]: hasVariant(
            $state,
            "variants",
            "wide"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__zRhf9, {
            [sty.freeBoxvariants_wide__zRhf9H3VVh]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__wPree
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___2EVam
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__yDciX)}
            role={"img"}
          />
        </div>

        <div
          className={classNames(projectcss.all, sty.freeBox__kTkYl, {
            [sty.freeBoxvariants_wide__kTkYLh3VVh]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__q9Ug,
              {
                [sty.textvariants_wide__q9UGh3VVh]: hasVariant(
                  $state,
                  "variants",
                  "wide"
                )
              }
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__t4S5
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg___5JTrz)}
            role={"img"}
          />
        </div>

        <div
          className={classNames(projectcss.all, sty.freeBox__dss6C, {
            [sty.freeBoxvariants_wide__dss6Ch3VVh]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__sfgt2
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hWt5P
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__jGsZn)}
            role={"img"}
          />
        </div>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandmarks__ArgProps,
          internalVariantPropNames: PlasmicLandmarks__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLandmarks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandmarks";
  } else {
    func.displayName = `PlasmicLandmarks.${nodeName}`;
  }
  return func;
}

export const PlasmicLandmarks = Object.assign(
  // Top-level PlasmicLandmarks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLandmarks
    internalVariantProps: PlasmicLandmarks__VariantProps,
    internalArgProps: PlasmicLandmarks__ArgProps
  }
);

export default PlasmicLandmarks;
/* prettier-ignore-end */
