// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3zC4fkbXrqgM7fa4uUQ6gc
// Component: ug8AQhEcKzWj5
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_abc.module.css"; // plasmic-import: 3zC4fkbXrqgM7fa4uUQ6gc/projectcss
import sty from "./PlasmicCompletedTestimonial.module.css"; // plasmic-import: ug8AQhEcKzWj5/css
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: GueOIOwUk-ilA/icon
import image450FYlVlWz8LZwQ from "./images/image45.png"; // plasmic-import: 0FYlVlWz8LZwQ/picture

export const PlasmicCompletedTestimonial__VariantProps = new Array();

export const PlasmicCompletedTestimonial__ArgProps = new Array();

function PlasmicCompletedTestimonial__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"100px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"none"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"100px"}
        src={{
          src: image450FYlVlWz8LZwQ,
          fullWidth: 205,
          fullHeight: 208,
          aspectRatio: undefined
        }}
      />

      <Icon28Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <div className={classNames(projectcss.all, sty.freeBox__z3HwA)}>
        <div className={classNames(projectcss.all, sty.freeBox__m2IPw)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___12P1D
            )}
          >
            {"Truly revolutionary. An incredible leap forward."}
          </div>
        </div>
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__d066I)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__dlF)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__f562Z
            )}
          >
            {"Jane Doe"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__rcr3G
            )}
          >
            {"VP Marketing\nPied Piper"}
          </div>
        </div>
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "svg"],
  img: ["img"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCompletedTestimonial__ArgProps,
          internalVariantPropNames: PlasmicCompletedTestimonial__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCompletedTestimonial__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedTestimonial";
  } else {
    func.displayName = `PlasmicCompletedTestimonial.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedTestimonial = Object.assign(
  // Top-level PlasmicCompletedTestimonial renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicCompletedTestimonial
    internalVariantProps: PlasmicCompletedTestimonial__VariantProps,
    internalArgProps: PlasmicCompletedTestimonial__ArgProps
  }
);

export default PlasmicCompletedTestimonial;
/* prettier-ignore-end */
